# fpm pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fpm-pv
spec:
  storageClassName: manual
  capacity: 
    storage: 100M
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /home/ec2-user/php-fpm-socket
---
# fpm pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fpm-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M